<scrape_config>
# The job name assigned to scraped metrics by default.
job_name: scraper

# How frequently to scrape targets from this job. This overwrites the default = <global_config.scrape_interval> 
[scrape_interval: 5s]

# The HTTP resource path on which to fetch metrics from targets. default = /metrics
[metrics_path: /data/metrics]

basic_auth:
  [ username: <string> ]
  [ password: <secret> ]
  [ password_file: <string> ]

# myuser: $2y$12$ZcEJGmnIDSMKaeJhZsYeNukC.aJ.RhIfypct/pK5psrHEh6cB79L6

# Configures the protocol scheme used for requests. | default = http 
[ scheme: https ]

